# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package SimpleDS;
use base qw(Exporter);
use base qw(DynaLoader);
package SimpleDSc;
bootstrap SimpleDS;
package SimpleDS;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package SimpleDS;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package SimpleDS;

*calculateArea = *SimpleDSc::calculateArea;

############# Class : SimpleDS::Rectangle ##############

package SimpleDS::Rectangle;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( SimpleDS );
%OWNER = ();
%ITERATORS = ();
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        SimpleDSc::delete_Rectangle($self);
        delete $OWNER{$self};
    }
}

sub new {
    my $pkg = shift;
    my $self = SimpleDSc::new_Rectangle(@_);
    bless $self, $pkg if defined($self);
}

*area = *SimpleDSc::Rectangle_area;
*show = *SimpleDSc::Rectangle_show;
*clone = *SimpleDSc::Rectangle_clone;
*classInfo = *SimpleDSc::Rectangle_classInfo;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package SimpleDS;

*pi = *SimpleDSc::pi;
*RED = *SimpleDSc::RED;
1;
